---
- name: examplae playbook with loop kind of work
  hosts: all 
  become: yes
  tasks: 
    - name: add list of users in my nodes
      user:                              #user = module
        name: "{{ item }}"               #mention in with items
        state: present
      with_items:                        #with items is module
        - jarvis
        - spider               #script will be executed until items will created
                               # it will be executed by 2 times
                               #when you have to create new user just change the items values