---
- name: take input from user
  hosts: all
  vars_prompt:
    - name: username
      prompt: please enter your name
      private: no                                    #--- display on screen
    - name: password
      prompt: please enter your password             
      private: yes                                   #--- not display
  tasks:
    - debug:
        msg: "The username is {{username}} and password is {{password}}"