---
- name: pass value using prompt
  hosts: all
  vars_prompt:
    - name: dhananjay
      prompt: "password"
  vars:
    URL: "dhananjay.com"
  tasks:
    - name: 1st prompt in file
      debug:
        msg: "{{dhananjay}}"
      debug:
        msg: "{{URL}}"
...
